# -*- coding: utf-8 -*-
"""mobile_apps_reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKuyxsTXw6H-pOxzytb_dn399jq8tv-V
"""

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Dataset/multilingual_mobile_app_reviews_2025.csv')

df.head()

df.tail()

df.info()

df.shape

df.describe()

df.columns

col_list=['review_id', 'user_id', 'app_name', 'app_category', 'review_text',
       'review_language', 'rating', 'review_date', 'verified_purchase',
       'device_type', 'num_helpful_votes', 'user_age', 'user_country',
       'user_gender', 'app_version']
col_list

df.isnull()

df. columns.value_counts()

for i in df.columns:
  if df[i].dtype=='object':
    df[i]=df[i].fillna(df[i].mode()[0])
  else:
    df[i]=df[i].fillna(df[i].mean())

import matplotlib.pyplot as plt
for i in df.columns:
  if (df[i].dtype !='object') and (i !='charges') and (df[i].dtype != 'bool'):
    plt.boxplot(df[i])
    plt.xlabel(i)
    plt.show()

for i in col_list:
  if df[i].dtype != 'object' and df[i].dtype != 'bool':
    Q1=df[i].quantile(0.25)
    Q3=df[i].quantile(0.75)
    IQR=Q3-Q1
    lower_limit=Q1-1.5*IQR
    upper_limit=Q3+1.5*IQR
    df[(df[i]<lower_limit) & (df[i]>upper_limit)]

df.head()

col_list=[]
for i in df.columns:
  if((df[i].dtype !='object') & (i !='charges')):
    col_list.append(i)

col_list

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in col_list:
  df[i]=le.fit_transform(df[i])

col_list

from statsmodels.stats.outliers_influence import variance_inflation_factor
x = df[col_list]
vif_data = pd.DataFrame()
vif_data['feature'] = x.columns
vif_data['VIF'] = [variance_inflation_factor(x.values, i) for i in range(len(x.columns))]

display(vif_data)

from sklearn.model_selection import train_test_split
x = df[['review_id','user_id','verified_purchase','num_helpful_votes','user_age']]
y = df['rating']



x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)